- hosts: localhost
  connection: local
  become: true
  tasks:
  - name: "Update repositories cache Ubuntu"
    apt:
      update_cache: yes
    when: ansible_facts['os_family'] == "Debian"
  - name: "Update repositories cache Ubuntu"
    apt:
      upgrade: true
      state: latest
    when: 
      - ansible_facts['os_family'] == "Debian"
      - keep_packages_updated  

  - name: Install apt packages
    ansible.builtin.package:
      name:
        - vim
        - git
        - apt-transport-https
        - curl
        - iptables-persistent
        - wget
        - htop
        - software-properties-common
        - neofetch
        - tmux
        - nload
        - autossh
      state: latest
  - name: Create a directory if it does not exist
    ansible.builtin.file:
      path: /home/drok/.ssh
      state: directory
      owner: drok
      group: drok
      mode: '0700'
  - name: Copy file with owner and permissions
    ansible.builtin.copy:
      src: ssh.pub
      dest: /home/drok/.ssh/authorized_keys
      owner: drok
      group: drok
      mode: '0644'

- hosts: localhost
  connection: local
  become: true
  vars:
    swap_file_size_mb: '8192'
    security_sudoers_passworded:
      - drok
    security_autoupdate_mail_to: "drok@drokdev.pro"
    security_autoupdate_mail_on_error: true
    security_ssh_port: 2020
    firewall_disable_ufw: true
    firewall_disable_firewalld: true
    firewall_allowed_tcp_ports:
      - "2020"
      - "89"
      # - "12798"
      # - "9091"
      # - "3000"
      # - "5000"
      # - "9090"
    # firewall_additional_rules:
    #   - "iptables -A INPUT --proto icmp -j DROP"
  roles:
    - geerlingguy.swap
    - geerlingguy.clamav
    - geerlingguy.security
    - geerlingguy.firewall

